### ISSUE TITLE
[Bug] `Manager.add` not working for paths

### ISSUE THREAD

**Issue by gastonalonso** [jakehamilton/leverage#22]
Manager crashes with error `TypeError: require_dir_all_1.default is not a function` when given a path. Apparently this is caused by the 'require-dir-all' module no being imported correctly.

**Comment by jakehamilton** [comment]
I think this is happening because of synthetic imports in TS. For now I suggest using `require-dir-all`  manually to add your units:

```ts
// Notice the "* as name" pattern instead of using the default export (which doesn't exist)
import * as requireDir from 'require-dir-all';

import { Manager } from '@leverage/core';

const units = requireDir('/path/to/dir');

const manager = new Manager();

manager.add(units);
```

This issue will be fixed in the next patch.
